kumuluzee:
  name: greo-spilat
  version: 1.0.0
  env:
    name: dev
  datasources:
    - jndi-name: jdbc/sportappDS
      connection-url: jdbc:postgresql://localhost:5432/sportapp
      username: luka
      password: luka
      max-pool-size: 20
  health:
    checks:
      data-source-health-check:
        type: liveness
        jndi-name: jdbc/sport-appDS
  rest-client:
    registrations:
      - class: sport-app-api
        url: http://localhost:8081/v1
        read-timeout: 5000
integrations:
  sport-app:
    base-url: http://localhost:8081/v1