apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.35.0 (HEAD)
  labels:
    io.kompose.service: auth-service
  name: auth-service
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: auth-service
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.35.0 (HEAD)
      labels:
        io.kompose.service: auth-service
    spec:
      containers:
        - name: auth-service
          image: lukaexmedicinec/prpo-ll:auth-service
          ports:
            - containerPort: 8085
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /health/live
              port: 8085
            initialDelaySeconds: 10
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /health/ready
              port: 8085
            initialDelaySeconds: 5
            periodSeconds: 5
      restartPolicy: Always
