kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: greo-spilat
nodes:
- role: control-plane
  extraPortMappings:
    - containerPort: 5432
      hostPort: 5432
      protocol: TCP
    - containerPort: 8085
      hostPort: 8085
      protocol: TCP
    - containerPort: 8084
      hostPort: 8084
      protocol: TCP
    - containerPort: 8083
      hostPort: 8083
      protocol: TCP
